#ifndef CONSTANTS_H
#define CONSTANTS_H


#define DRV_DISKNAME_MAX 32

#define DRV_OP_SUCCESS 0
#define DRV_NSECTORS 50 * 1024 * 2
#define DRV_SECTOR_SZ 512
#define DRV_MINORS 16

#define KERNEL_SECTOR_SIZE 512


#endif